# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Midas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Midas
   pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
   pod 'TensorFlowLiteSwift/CoreML', '~> 0.0.1-nightly'
   pod 'TensorFlowLiteSwift/Metal', '~> 0.0.1-nightly'
end
